<a href="https://colab.research.google.com/github/thiagosoalheiro/Aula_Sustentabilida_1CCA/blob/main/Solu_Sustent_Aula_4_Analise_de_Dados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Exemplo - Análise de Dados de Consumidores de Nergia Elétrica

In [ ]:
# IMPORTANDO BIBLIOTECA PARA MANIPULAÇÃO DE TABELAS
import pandas as pd

In [ ]:
tabela = pd.read_csv('/content/BASE_DE_DADOS.csv')

In [ ]:
# DIMENSÕES DA TABELA
tabela.shape

(204928, 9)

In [ ]:
tabela.columns

Index(['Date', 'Time', 'Global_active_power', 'Global_reactive_power',
       'Voltage', 'Global_intensity', 'Sub_metering_1', 'Sub_metering_2',
       'Sub_metering_3'],
      dtype='object')

In [ ]:
# VISUALIZANDO PRIMEIROS REGISTROS DA TABELA
  # LINHAS ---> " registros "
  # COLUNAS ---> " atributos " ---> " features "
tabela.head()

,Date,Time,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3
0,2008-01-12 00:00:00,2026-03-31 09:44:00,1.502,0.074,240.17,6.4,0,0,18
1,2006-12-17 00:00:00,2026-03-31 23:39:00,0.374,0.264,245.50,1.8,0,2,0
2,2009-03-06 00:00:00,2026-03-31 17:01:00,0.620,0.300,239.85,3.0,0,1,1
3,2007-09-05 00:00:00,2026-03-31 05:53:00,0.280,0.200,235.72,1.4,0,0,0
4,2008-12-14 00:00:00,2026-03-31 02:57:00,1.372,0.054,243.95,5.6,0,0,18

In [ ]:
tabela.columns

Index(['Date', 'Time', 'Global_active_power', 'Global_reactive_power',
       'Voltage', 'Global_intensity', 'Sub_metering_1', 'Sub_metering_2',
       'Sub_metering_3'],
      dtype='object')

In [ ]:
# ESTATISTICAS DESCRITIVAS DAS COLUNAS
# EXEMPLO: VOLTAGE (TENSÃO, EM VOLTS) E GLOBAL_INTENSITY (CORRENTE, EM AMPÉRES)

# VOLTAGE

# MÉDIA ARITMÉTICA
media_tensao = tabela['Voltage'].mean()
print(f"A média da tensão será de: {media_tensao:.2f}V")

# MEDIANA
mediana_tensao = tabela['Voltage'].median()
print(f"A mediana da tensão será de: {mediana_tensao:.2f}V")

# DESVIO PADRÃO
desvio_padrao = tabela['Voltage'].std()
print(f"O desvio padrão da tensão será de: {desvio_padrao:.2f}V")

A média da tensão será de: 240.83V
A mediana da tensão será de: 241.00V
O desvio padrão da tensão será de: 3.25V

In [ ]:
# GLOBAL_INTENSITY

# MÉDIA ARITMÉTICA
media_corrente = tabela['Global_intensity'].mean()
print(f"A média da corrente será de: {media_corrente:.2f}A")

# MEDIANA
mediana_corrente = tabela['Global_intensity'].median()
print(f"A mediana da corrente será de: {mediana_corrente:.2f}A")

# DESVIO PADRÃO
desvio_corrente = tabela['Global_intensity'].std()
print(f"O desvio padrão da corrente será de: {desvio_corrente:.2f}A")

A média da corrente será de: 4.63A
A mediana da corrente será de: 2.60A
O desvio padrão da corrente será de: 4.47A

In [ ]:
tabela.head()

,Date,Time,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3
0,2008-01-12 00:00:00,2026-03-31 09:44:00,1.502,0.074,240.17,6.4,0,0,18
1,2006-12-17 00:00:00,2026-03-31 23:39:00,0.374,0.264,245.50,1.8,0,2,0
2,2009-03-06 00:00:00,2026-03-31 17:01:00,0.620,0.300,239.85,3.0,0,1,1
3,2007-09-05 00:00:00,2026-03-31 05:53:00,0.280,0.200,235.72,1.4,0,0,0
4,2008-12-14 00:00:00,2026-03-31 02:57:00,1.372,0.054,243.95,5.6,0,0,18

In [ ]:
# ADICIONANDO UMA COLUNA COM POTÊNCIA APARENTE CALCULADA

# POTÊNCIA APARENTE = TENSÃO X CORRENTE
tabela['Pot_Calc_1'] = tabela['Voltage'] * tabela['Global_intensity']
tabela.head()

# Pot_Calc_2 = (Global_active_power**2 + Global_reactive_power**2)**0.5

,Date,Time,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3,Pot_Calc_1
0,2008-01-12 00:00:00,2026-03-31 09:44:00,1.502,0.074,240.17,6.4,0,0,18,1537.088
1,2006-12-17 00:00:00,2026-03-31 23:39:00,0.374,0.264,245.50,1.8,0,2,0,441.900
2,2009-03-06 00:00:00,2026-03-31 17:01:00,0.620,0.300,239.85,3.0,0,1,1,719.550
3,2007-09-05 00:00:00,2026-03-31 05:53:00,0.280,0.200,235.72,1.4,0,0,0,330.008
4,2008-12-14 00:00:00,2026-03-31 02:57:00,1.372,0.054,243.95,5.6,0,0,18,1366.120